# .github/workflows/autofix.yml

name: CI - Автоисправление стиля кода

on:
  push:
    branches: [ main, develop ]

jobs:
  autofix:
    name: FIX 🎨 Автоматическое исправление (autopep8)
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код из репозитория
      - name: ⬇️ Получение кода
        uses: actions/checkout@v4
        with:
          # Нужен токен, чтобы коммитить изменения обратно в репо
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Настраиваем Python 3.10
      - name: 🐍 Настройка Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Устанавливаем автоформаттер
      - name: 📦 Установка autopep8
        run: |
          pip install autopep8

      # 4. ЗАПУСК АВТОИСПРАВЛЕНИЯ
      # autopep8 исправит все ошибки E* и W* (отступы, пробелы и т.д.)
      - name: 🎨 Запуск автоисправления
        run: |
          echo "🤖 Запускаю исправление форматирования..."
          # --in-place : исправить файлы на месте
          # --recursive . : для всех .py файлов в проекте
          # --aggressive --aggressive : применяет более мощные (но безопасные) правила
          autopep8 --in-place --recursive . --aggressive --aggressive

      # 5. Сохранение (коммит) изменений
      # Этот шаг проверит, были ли внесены исправления
      # Если да - он создаст новый коммит от имени "GitHub Actions"
      - name: 💾 Сохранение исправлений
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Автоматически исправлен стиль кода (autopep8)"
          commit_user_name: GitHub Actions [bot]
          commit_user_email: actions@github.com
          commit_author: GitHub Actions [bot] <actions@github.com>
