name: Type Checking (mypy)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  mypy:
    name: Run Mypy Type Checker
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Убедитесь, что версия совпадает

      - name: 📦 Install mypy and dependencies
        run: |
          pip install mypy
          # Установка типов для используемых библиотек (если они есть)
          pip install types-requests # Пример для requests
          # Добавьте сюда установку других пакетов типов, если необходимо
          pip install -r requirements.txt # Устанавливаем зависимости проекта

      - name: 🤔 Run Mypy
        run: mypy . --ignore-missing-imports --explicit-package-bases
        # --ignore-missing-imports игнорирует ошибки, если у библиотеки нет файлов типов
        # --explicit-package-bases может понадобиться для корректной работы с вашей структурой импортов